source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
platform :ios,'9.0'
target 'ToolDemo' do
  use_frameworks!
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'MJRefresh', '~> 3.4.3'
end

target 'Tool' do
  use_frameworks!
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'MJRefresh', '~> 3.4.3'

end


